version: '3'
services:

  database:
    image: mysql:5.7
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./:/app:delegated
    environment:
      XDEBUG_CONFIG: "remote_enable=1 remote_host=host.docker.internal"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - database

  php-cli:
    build:
      context: ./docker/php-cli
    volumes:
      - ./:/app
      - composer:/root/.composer/cache
    environment:
      XDEBUG_CONFIG: "remote_enable=1 remote_host=host.docker.internal"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - database

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/app:delegated
    ports:
      - "8080:80"
    depends_on:
      - php-fpm

volumes:
  composer: